// frontend/src/components/groups/GroupFormDialog.tsx
// DESIGN SPEC — generated by Designer agent
// Coder: implement TODO items, do not change component structure or accessibility attributes

import { useState, useEffect } from "react";
import { Loader2 } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Group } from "./GroupTable";

// ============================================================================
// Types
// ============================================================================

export interface GroupFormData {
  name: string;
  description: string;
}

interface GroupFormDialogProps {
  mode: "create" | "edit";
  group?: Group | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSubmit: (data: GroupFormData) => Promise<void>;
  isLoading?: boolean;
}

// ============================================================================
// Validation
// ============================================================================

function validateGroupForm(data: GroupFormData): Record<string, string> {
  const errors: Record<string, string> = {};
  
  if (!data.name || data.name.trim().length === 0) {
    errors.name = "Group name cannot be empty";
  } else if (data.name.trim().length < 2) {
    errors.name = "Group name must be at least 2 characters";
  } else if (data.name.length > 100) {
    errors.name = "Group name must be less than 100 characters";
  }
  
  if (data.description && data.description.length > 500) {
    errors.description = "Description must be less than 500 characters";
  }
  
  return errors;
}

// ============================================================================
// Main Component
// ============================================================================

export function GroupFormDialog({
  mode,
  group,
  open,
  onOpenChange,
  onSubmit,
  isLoading = false,
}: GroupFormDialogProps): JSX.Element {
  const isEdit = mode === "edit";
  const title = isEdit ? "Edit Group" : "Create Group";
  const description = isEdit
    ? `Update details for ${group?.name || "this group"}`
    : "Create a new group to organize users and manage vault access.";
  const submitLabel = isEdit ? "Save Changes" : "Create Group";

  // Form state
  const [formData, setFormData] = useState<GroupFormData>({
    name: "",
    description: "",
  });
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [rootError, setRootError] = useState<string | null>(null);

  // Reset form when dialog opens/closes or group changes
  useEffect(() => {
    if (open) {
      if (isEdit && group) {
        setFormData({
          name: group.name,
          description: group.description || "",
        });
      } else {
        setFormData({
          name: "",
          description: "",
        });
      }
      setErrors({});
      setRootError(null);
    }
  }, [open, group, isEdit]);

  // ============================================================================
  // Event Handlers
  // ============================================================================

  const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData((prev) => ({ ...prev, name: e.target.value }));
    if (errors.name) {
      setErrors((prev) => ({ ...prev, name: "" }));
    }
  };

  const handleDescriptionChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setFormData((prev) => ({ ...prev, description: e.target.value }));
    if (errors.description) {
      setErrors((prev) => ({ ...prev, description: "" }));
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setRootError(null);
    
    // Validate
    const validationErrors = validateGroupForm(formData);
    if (Object.keys(validationErrors).length > 0) {
      setErrors(validationErrors);
      return;
    }
    
    try {
      await onSubmit(formData);
      // Form submission successful - dialog will be closed by parent
    } catch (error) {
      setRootError(error instanceof Error ? error.message : "An error occurred");
    }
  };

  // ============================================================================
  // Render
  // ============================================================================

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[425px]" aria-labelledby="form-title" aria-describedby="form-desc">
        <DialogHeader>
          <DialogTitle id="form-title">{title}</DialogTitle>
          <DialogDescription id="form-desc">{description}</DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit}>
          <div className="grid gap-4 py-4">
            {/* Root Error */}
            {rootError && (
              <div
                role="alert"
                aria-live="polite"
                className="rounded-md border border-destructive/50 bg-destructive/10 p-3 text-sm text-destructive"
              >
                {rootError}
              </div>
            )}

            {/* Name Field */}
            <div className="grid gap-2">
              <Label htmlFor="group-name">
                Group Name <span className="text-destructive">*</span>
              </Label>
              <Input
                id="group-name"
                type="text"
                autoComplete="off"
                disabled={isLoading}
                aria-invalid={!!errors.name}
                aria-describedby={errors.name ? "group-name-error" : undefined}
                value={formData.name}
                onChange={handleNameChange}
              />
              {errors.name && (
                <p id="group-name-error" className="text-sm text-destructive">
                  {errors.name}
                </p>
              )}
            </div>

            {/* Description Field */}
            <div className="grid gap-2">
              <Label htmlFor="group-description">Description</Label>
              <Textarea
                id="group-description"
                rows={3}
                disabled={isLoading}
                placeholder="Enter group description (optional)"
                aria-invalid={!!errors.description}
                aria-describedby={errors.description ? "group-desc-error" : undefined}
                value={formData.description}
                onChange={handleDescriptionChange}
              />
              {errors.description && (
                <p id="group-desc-error" className="text-sm text-destructive">
                  {errors.description}
                </p>
              )}
            </div>
          </div>

          <DialogFooter className="flex-col gap-2 sm:flex-row">
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
              disabled={isLoading}
              className="w-full sm:w-auto"
            >
              Cancel
            </Button>
            <Button
              type="submit"
              disabled={isLoading}
              className="w-full sm:w-auto"
              aria-label={submitLabel}
            >
              {isLoading ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" aria-hidden="true" />
                  {isEdit ? "Saving..." : "Creating..."}
                </>
              ) : (
                submitLabel
              )}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

export default GroupFormDialog;
