// frontend/src/components/groups/ManageVaultsSheet.tsx
// DESIGN SPEC — generated by Designer agent
// Coder: implement TODO items, do not change component structure or accessibility attributes

import { useState, useEffect, useCallback } from "react";
import { useQuery } from "@tanstack/react-query";
import { Loader2, FolderOpen, Search, Shield } from "lucide-react";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Skeleton } from "@/components/ui/skeleton";
import {
  type Group,
  type Vault,
  getGroupVaultIds,
  listVaults,
} from "@/lib/api";

// ============================================================================
// Types
// ============================================================================

interface ManageVaultsSheetProps {
  group: Group | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSave: (vaultIds: number[]) => Promise<void>;
}

// ============================================================================
// Main Component
// ============================================================================

export function ManageVaultsSheet({
  group,
  open,
  onOpenChange,
  onSave,
}: ManageVaultsSheetProps): JSX.Element {
  const [selectedVaultIds, setSelectedVaultIds] = useState<number[]>([]);
  const [searchQuery, setSearchQuery] = useState("");
  const [isSaving, setIsSaving] = useState(false);

  // Fetch all vaults and current group vault access
  const { data: allVaults = [], isLoading: isLoadingVaults } = useQuery<Vault[]>({
    queryKey: ["vaults"],
    queryFn: async () => {
      const resp = await listVaults();
      return resp.vaults;
    },
    enabled: open,
  });

  const { data: groupVaultIds = [], isLoading: isLoadingAccess } = useQuery<number[]>({
    queryKey: ["groups", group?.id, "vaults"],
    queryFn: () => getGroupVaultIds(group!.id),
    enabled: open && !!group,
  });

  // Initialize vault access when sheet opens
  useEffect(() => {
    if (open && groupVaultIds) {
      setSelectedVaultIds(groupVaultIds);
    }
  }, [open, groupVaultIds]);

  // Reset search when sheet closes
  useEffect(() => {
    if (!open) {
      setSearchQuery("");
    }
  }, [open]);

  // ============================================================================
  // Event Handlers
  // ============================================================================

  const toggleVault = useCallback((vaultId: number) => {
    setSelectedVaultIds((prev) =>
      prev.includes(vaultId)
        ? prev.filter((id) => id !== vaultId)
        : [...prev, vaultId]
    );
  }, []);

  const handleSave = useCallback(async () => {
    setIsSaving(true);
    try {
      await onSave(selectedVaultIds);
    } finally {
      setIsSaving(false);
    }
  }, [selectedVaultIds, onSave]);

  // ============================================================================
  // Filtered Vaults
  // ============================================================================

  const filteredVaults = allVaults.filter((vault) => {
    const searchLower = searchQuery.toLowerCase();
    return (
      vault.name.toLowerCase().includes(searchLower) ||
      (vault.description && vault.description.toLowerCase().includes(searchLower))
    );
  });

  // ============================================================================
  // Helpers
  // ============================================================================

  const selectedCount = selectedVaultIds.length;

  // ============================================================================
  // Loading State
  // ============================================================================

  const isLoading = isLoadingVaults || isLoadingAccess;

  // ============================================================================
  // Render
  // ============================================================================

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent className="sm:max-w-[450px] flex flex-col" aria-labelledby="vaults-title" aria-describedby="vaults-desc">
        <SheetHeader>
          <SheetTitle id="vaults-title" className="flex items-center gap-2">
            <FolderOpen className="h-5 w-5" aria-hidden="true" />
            Manage Vault Access
          </SheetTitle>
          <SheetDescription id="vaults-desc">
            Configure vault access permissions for <strong>{group?.name}</strong>. 
            Set permission level for each vault or remove access.
          </SheetDescription>
        </SheetHeader>

        <div className="flex-1 flex flex-col py-4 min-h-0">
          {/* Search Input */}
          <div className="relative mb-4">
            <Search
              className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"
              aria-hidden="true"
            />
            <Input
              placeholder="Search vaults..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-10"
              aria-label="Search vaults"
              disabled={isLoading}
            />
          </div>

          {/* Vaults List */}
          <ScrollArea className="flex-1 -mx-6 px-6">
            {isLoading ? (
              <div className="space-y-3">
                {Array.from({ length: 5 }).map((_, i) => (
                  <div key={i} className="p-3 rounded-md border space-y-2">
                    <Skeleton className="h-4 w-32" />
                    <Skeleton className="h-3 w-full" />
                    <Skeleton className="h-9 w-32" />
                  </div>
                ))}
              </div>
            ) : filteredVaults.length === 0 ? (
              <div className="text-center py-8 text-muted-foreground" role="status" aria-live="polite">
                {searchQuery ? "No vaults match your search" : "No vaults available"}
              </div>
            ) : (
              <div className="space-y-2 pr-4">
                {filteredVaults.map((vault) => {
                  const hasAccess = selectedVaultIds.includes(vault.id);

                  return (
                    <div
                      key={vault.id}
                      className={`flex items-start space-x-3 rounded-md border p-3 transition-colors ${
                        hasAccess ? "border-primary/50 bg-primary/5" : "hover:bg-muted/50"
                      }`}
                    >
                      <Checkbox
                        id={`vault-${vault.id}`}
                        checked={hasAccess}
                        onCheckedChange={() => toggleVault(vault.id)}
                        aria-label={`Grant access to ${vault.name}`}
                        disabled={isSaving}
                      />
                      <Label
                        htmlFor={`vault-${vault.id}`}
                        className="flex-1 cursor-pointer space-y-1"
                      >
                        <div className="flex items-center gap-2">
                          <FolderOpen className="h-4 w-4 text-muted-foreground flex-shrink-0" aria-hidden="true" />
                          <span className="font-medium">{vault.name}</span>
                          {hasAccess && (
                            <Shield className="h-3 w-3 text-primary flex-shrink-0" aria-hidden="true" />
                          )}
                        </div>
                        {vault.description && (
                          <p className="text-sm text-muted-foreground line-clamp-2">
                            {vault.description}
                          </p>
                        )}
                      </Label>
                    </div>
                  );
                })}
              </div>
            )}
          </ScrollArea>



          {/* Selected Count */}
          <div className="mt-4 text-sm text-muted-foreground">
            {selectedCount} vault{selectedCount !== 1 ? "s" : ""} with access
          </div>
        </div>

        <SheetFooter className="flex-col gap-2 sm:flex-row border-t pt-4">
          <Button
            type="button"
            variant="outline"
            onClick={() => onOpenChange(false)}
            disabled={isSaving}
            className="w-full sm:w-auto"
          >
            Cancel
          </Button>
          <Button
            onClick={handleSave}
            disabled={isSaving || isLoading}
            className="w-full sm:w-auto"
            aria-label="Save vault access changes"
          >
            {isSaving ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" aria-hidden="true" />
                Saving...
              </>
            ) : (
              "Save Changes"
            )}
          </Button>
        </SheetFooter>
      </SheetContent>
    </Sheet>
  );
}

export default ManageVaultsSheet;
