"""
Contextual chunking service using LLM to generate context prefixes for document chunks.

This service enhances chunks with context generated by an LLM to improve retrieval
quality by providing document-level context to each chunk.
"""

import asyncio
import json
import logging
from typing import List

from app.config import settings
from app.services.chunking import ProcessedChunk
from app.services.llm_client import LLMClient, LLMError

logger = logging.getLogger(__name__)


def _sanitize_filename(filename: str) -> str:
    """
    Sanitize a filename by removing non-printable characters and path separators.

    Removes:
    - Control characters (ASCII 0-31 except tab, newline, carriage return)
    - Path separators (/ and \\)
    - Colon (:) which is reserved on Windows
    - Other non-printable characters

    Args:
        filename: The raw filename string.

    Returns:
        A sanitized filename safe for use in prompts and logs.
    """
    import re

    # Remove control characters except tab, newline, CR
    sanitized = re.sub(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]", "", filename)
    # Remove path separators and drive colons
    sanitized = re.sub(r"[/\\:]", "", sanitized)
    # Strip leading/trailing whitespace
    sanitized = sanitized.strip()
    # Collapse multiple spaces
    sanitized = re.sub(r" +", " ", sanitized)
    # Return empty string if nothing left
    return sanitized if sanitized else "unknown_file"


class ContextualChunker:
    """
    Service for adding LLM-generated context to document chunks.

    Generates a short (1-2 sentence) context prefix for each chunk using an LLM,
    improving retrieval quality by providing document-level context.

    The service is stateless except for the concurrency semaphore, which limits
    the number of concurrent LLM calls to prevent overwhelming the LLM server.
    """

    # Maximum document length before truncation
    _MAX_DOCUMENT_LENGTH = 100_000
    # Characters to keep from start when truncating
    _TRUNCATE_CHARS = 50_000
    # Default concurrency limit
    _DEFAULT_CONCURRENCY = 5
    # Maximum tokens for context generation (per-chunk single calls)
    _MAX_TOKENS = 150

    def __init__(self, llm_client: LLMClient):
        """
        Initialize the contextual chunker.

        Args:
            llm_client: LLMClient instance for generating context.
                        Must be started before calling contextualize_chunks.
        """
        self._llm_client = llm_client
        # Get concurrency limit from settings, falling back to default
        concurrency = getattr(
            settings, "contextual_chunking_concurrency", self._DEFAULT_CONCURRENCY
        )
        self._semaphore = asyncio.Semaphore(concurrency)
        logger.info(
            f"ContextualChunker initialized with concurrency limit: {concurrency}"
        )

    def _truncate_document(self, document_text: str) -> str:
        """
        Truncate document text if it exceeds the maximum length.

        When the document exceeds _MAX_DOCUMENT_LENGTH characters, keeps the first
        _TRUNCATE_CHARS characters and the last _TRUNCATE_CHARS characters,
        with a [...] marker in between.

        Args:
            document_text: The full document text to potentially truncate.

        Returns:
            The document text, truncated if necessary.
        """
        if len(document_text) <= self._MAX_DOCUMENT_LENGTH:
            return document_text

        truncated = (
            document_text[: self._TRUNCATE_CHARS]
            + "\n\n[...truncated...]\n\n"
            + document_text[-self._TRUNCATE_CHARS :]
        )
        logger.warning(
            f"Document truncated from {len(document_text)} to {len(truncated)} characters"
        )
        return truncated

    def _build_prompt(
        self,
        document_text: str,
        chunk_text: str,
        chunk_index: int,
        total_chunks: int,
        source_filename: str,
    ) -> List[dict]:
        """
        Build the prompt for generating chunk context.

        Creates a prompt that asks the LLM to generate a short (1-2 sentence)
        context description that helps understand where this chunk fits in the
        overall document.

        Args:
            document_text: The (potentially truncated) full document text.
            chunk_text: The text content of the chunk to contextualize.
            chunk_index: The index of the chunk in the document.
            total_chunks: Total number of chunks in the document.
            source_filename: The name of the source file.

        Returns:
            List of message dicts for LLM chat completion.
        """
        return [
            {
                "role": "system",
                "content": "You are a helpful assistant that generates brief context "
                "descriptions for document chunks. Generate a short (1-2 sentence) "
                "description that explains where this chunk fits in the document. "
                "Be concise and focus on the main topic or section.",
            },
            {
                "role": "user",
                "content": f"Source file: {source_filename}\n"
                f"Chunk {chunk_index + 1} of {total_chunks}\n\n"
                f"Full document (for context):\n"
                f"{document_text}\n\n"
                f"Chunk to contextualize:\n"
                f"{chunk_text}\n\n"
                f"Provide a brief context description (1-2 sentences) for this chunk.",
            },
        ]

    def _build_batch_prompt(
        self,
        document_text: str,
        chunks: list,  # list of chunk objects with .text attribute
        source_filename: str,
        chunk_indices: list,  # global indices for reference
    ) -> list:
        """Build a single prompt asking the LLM to contextualize N chunks at once."""
        chunks_section = ""
        for local_idx, (chunk, global_idx) in enumerate(zip(chunks, chunk_indices)):
            chunks_section += f'\n  {{"index": {local_idx}, "text": {json.dumps(chunk.text)}}}'

        return [
            {
                "role": "system",
                "content": (
                    "You are a document context expert. Given a document and a list of text chunks, "
                    "write a brief 1-2 sentence context for each chunk explaining what it covers "
                    "and how it fits in the document. "
                    "Respond ONLY with a JSON array, one object per chunk, in order: "
                    '[{"index": 0, "context": "..."}, {"index": 1, "context": "..."}, ...]. '
                    "No other text outside the JSON array."
                ),
            },
            {
                "role": "user",
                "content": (
                    f"Source file: {source_filename}\n\n"
                    f"Full document (for context):\n{document_text}\n\n"
                    f"Chunks to contextualize (JSON array):\n[{chunks_section}\n]\n\n"
                    "Respond with a JSON array of context objects in the same order."
                ),
            },
        ]

    def _parse_batch_response(self, response_text: str, expected_count: int) -> list:
        """
        Parse JSON batch response from LLM. Returns list of context strings in order.
        Raises ValueError if parsing fails or count mismatches.
        """
        # Strip markdown code fences if present
        text = response_text.strip()
        if text.startswith("```"):
            lines = text.split("\n")
            text = "\n".join(lines[1:-1] if lines[-1].strip() == "```" else lines[1:])

        parsed = json.loads(text)  # raises json.JSONDecodeError on failure

        if not isinstance(parsed, list):
            raise ValueError(f"Expected JSON array, got {type(parsed)}")
        if len(parsed) != expected_count:
            raise ValueError(
                f"Expected {expected_count} context items, got {len(parsed)}"
            )

        # Sort by index to ensure order (LLM may reorder)
        parsed.sort(key=lambda x: x.get("index", 0))

        contexts = []
        for item in parsed:
            context = item.get("context", "").strip()
            if not context:
                raise ValueError(f"Empty context for chunk index {item.get('index')}")
            contexts.append(context)

        return contexts

    async def _contextualize_batch(
        self,
        document_text: str,
        chunks: list,
        source_filename: str,
        chunk_indices: list,
        batch_num: int,
    ) -> list:
        """
        Contextualize a batch of chunks in a single LLM call.
        Returns list of context strings (None for failed chunks).
        Falls back to per-chunk processing if batch fails.
        """
        batch_size = len(chunks)
        # Scale max_tokens with batch size: 200 tokens per chunk + 500 overhead
        batch_max_tokens = batch_size * 200 + 500

        messages = self._build_batch_prompt(document_text, chunks, source_filename, chunk_indices)

        for attempt in range(3):
            try:
                response = await self._llm_client.chat_completion(
                    messages=messages,
                    max_tokens=batch_max_tokens,
                )
                contexts = self._parse_batch_response(response, batch_size)
                logger.debug(
                    "Batch %d: contextualized %d chunks in one LLM call",
                    batch_num,
                    batch_size,
                )
                return contexts
            except (ValueError, json.JSONDecodeError) as parse_err:
                logger.warning(
                    "Batch %d attempt %d: parse failed (%s), %s",
                    batch_num,
                    attempt + 1,
                    parse_err,
                    "retrying" if attempt < 2 else "falling back to per-chunk",
                )
                if attempt < 2:
                    await asyncio.sleep(0.5 * (2 ** attempt))
                    continue
                # After 3 parse failures, return None for all — caller falls back per-chunk
                return [None] * batch_size
            except Exception as exc:
                logger.warning(
                    "Batch %d attempt %d: LLM error (%s), %s",
                    batch_num,
                    attempt + 1,
                    exc,
                    "retrying" if attempt < 2 else "falling back to per-chunk",
                )
                if attempt < 2:
                    await asyncio.sleep(0.5 * (2 ** attempt))
                    continue
                return [None] * batch_size

        return [None] * batch_size

    async def contextualize_chunks(
        self, document_text: str, chunks: List[ProcessedChunk], source_filename: str
    ) -> List[ProcessedChunk]:
        """
        Add LLM-generated context to each chunk in the document.

        Uses batched LLM calls (configurable batch size) to reduce the number of
        LLM requests. Each batch sends multiple chunks in a single call and parses
        JSON responses. Falls back to per-chunk processing if a batch fails.

        Args:
            document_text: The full document text.
            chunks: List of ProcessedChunk objects to contextualize.
            source_filename: The name of the source file for context.

        Returns:
            The same chunks list with context added to each chunk's text,
            with metadata['contextualized'] set to True on success or False on failure.
        """
        if not chunks:
            logger.debug("No chunks to contextualize")
            return chunks

        # Truncate document if too long
        truncated_doc = self._truncate_document(document_text)

        total_chunks = len(chunks)
        safe_filename = _sanitize_filename(source_filename)
        logger.info(f"Contextualizing {total_chunks} chunks for file: {safe_filename}")

        batch_size = getattr(settings, "contextual_chunking_batch_size", 10)

        # Split chunks into batches
        batches = []
        for batch_start in range(0, total_chunks, batch_size):
            batch_chunks = chunks[batch_start : batch_start + batch_size]
            batch_indices = list(range(batch_start, batch_start + len(batch_chunks)))
            batches.append((batch_chunks, batch_indices))

        logger.info(
            f"Processing {total_chunks} chunks in {len(batches)} batches (batch_size={batch_size})"
        )

        async def process_batch(batch_num: int, batch_chunks: list, batch_indices: list) -> None:
            async with self._semaphore:
                contexts = await self._contextualize_batch(
                    document_text=truncated_doc,
                    chunks=batch_chunks,
                    source_filename=safe_filename,
                    chunk_indices=batch_indices,
                    batch_num=batch_num,
                )

            # Apply results; fall back per-chunk for any None entries
            for chunk, global_idx, context in zip(batch_chunks, batch_indices, contexts):
                if context is not None:
                    context = context.strip()
                    if context:
                        chunk.raw_text = chunk.text
                        chunk.text = f"{context}\n\n{chunk.text}"
                        logger.debug(
                            "Added batch context to chunk %d: %s...",
                            global_idx,
                            context[:50],
                        )
                        chunk.metadata["contextualized"] = True
                    else:
                        logger.warning("Empty context string for chunk %d after batch", global_idx)
                        chunk.metadata["contextualized"] = True
                else:
                    # Batch failed for this chunk — fall back to individual call
                    logger.debug(
                        "Batch returned None for chunk %d, falling back to per-chunk", global_idx
                    )
                    try:
                        await self._contextualize_single_chunk(
                            chunk=chunk,
                            document_text=truncated_doc,
                            chunk_index=global_idx,
                            total_chunks=total_chunks,
                            source_filename=safe_filename,
                        )
                    except Exception:
                        # _contextualize_single_chunk sets metadata["contextualized"]=False
                        # before re-raising; swallow here so remaining chunks are processed.
                        chunk.metadata.setdefault("contextualized", False)

        tasks = [
            process_batch(batch_num, batch_chunks, batch_indices)
            for batch_num, (batch_chunks, batch_indices) in enumerate(batches)
        ]

        await asyncio.gather(*tasks)

        logger.info(f"Completed contextualization for {total_chunks} chunks")

        return chunks

    async def _contextualize_single_chunk(
        self,
        chunk: ProcessedChunk,
        document_text: str,
        chunk_index: int,
        total_chunks: int,
        source_filename: str,
    ) -> None:
        """
        Generate and add context to a single chunk.

        Uses the LLM to generate a context prefix and prepends it to the
        chunk text. Always sets contextualized=True in metadata, even on failure.

        Args:
            chunk: The ProcessedChunk to modify.
            document_text: The truncated document text for context.
            chunk_index: The index of this chunk.
            total_chunks: Total number of chunks.
            source_filename: Source filename for the prompt.
        """
        async with self._semaphore:
            try:
                prompt = self._build_prompt(
                    document_text=document_text,
                    chunk_text=chunk.text,
                    chunk_index=chunk_index,
                    total_chunks=total_chunks,
                    source_filename=source_filename,
                )

                # Retry loop with exponential backoff for transient LLM failures
                max_attempts = 3
                delays = [0.5, 1.0, 2.0]  # seconds
                last_error = None
                context = ""  # Initialize to satisfy type checker

                for attempt in range(max_attempts):
                    try:
                        context = await self._llm_client.chat_completion(
                            messages=prompt,
                            temperature=0.3,
                            max_tokens=self._MAX_TOKENS,
                        )
                        break  # Success
                    except LLMError as e:
                        last_error = e
                        if attempt < max_attempts - 1:
                            delay = delays[attempt]
                            logger.warning(
                                f"LLM error on attempt {attempt + 1}/{max_attempts} for chunk "
                                f"{chunk_index} (retry in {delay}s): {e}"
                            )
                            await asyncio.sleep(delay)
                        else:
                            logger.warning(
                                f"LLM error on final attempt for chunk {chunk_index}: {e}"
                            )
                            raise  # Re-raise to be caught by outer handler

                # Strip whitespace and check if we got a valid response
                context = context.strip()

                if context:
                    # Preserve raw text before contextual enrichment
                    chunk.raw_text = chunk.text
                    # Prepend context to chunk text for embedding (search uses enriched text)
                    chunk.text = f"{context}\n\n{chunk.text}"
                    logger.debug(
                        f"Added context to chunk {chunk_index}: {context[:50]}..."
                    )
                else:
                    logger.warning(f"Empty context response for chunk {chunk_index}")

                chunk.metadata["contextualized"] = True  # Only on success
            except LLMError as e:
                logger.warning(
                    f"LLM error generating context for chunk {chunk_index}: {e}"
                )
                chunk.metadata["contextualized"] = False
            except Exception as e:
                logger.warning(
                    f"Unexpected error generating context for chunk {chunk_index}: {e}"
                )
                chunk.metadata["contextualized"] = False
                # Re-raise to avoid silent suppression (LLMError re-raised from inner handler
                # can still reach here if raised in same function scope)
                raise
