"""Query transformation service for step-back prompting."""

import hashlib
import json
import logging
import re
from collections import OrderedDict
from typing import List, Optional, Tuple

from app.config import settings
from app.services.llm_client import LLMClient

logger = logging.getLogger(__name__)


# Short / referential follow-up patterns. When the latest user message matches
# any of these, the retrieval query is rewritten using the prior turn instead
# of being searched literally — "try again" alone returns no useful evidence.
_FOLLOWUP_REGEX = re.compile(
    r"^\s*("
    r"try\s+again|again\s+please|again|"
    r"retry|regenerate|redo|"
    r"continue|go\s+on|keep\s+going|"
    r"more|more\s+please|tell\s+me\s+more|"
    r"expand|expand\s+on\s+that|elaborate|"
    r"in\s+more\s+detail|more\s+detail(s)?|"
    r"shorter|shorter\s+please|summari[sz]e|tl;?dr|"
    r"longer|longer\s+please|"
    r"that('?s)?\s+wrong|that('?s)?\s+not\s+right|no,\s*.*"
    r")[\s.\!\?]*$",
    re.IGNORECASE,
)


def is_followup_query(query: str) -> bool:
    """Return True when the user message is a short/referential follow-up.

    These messages lack standalone retrieval signal — they only make sense
    relative to the prior conversation turn. Examples: ``try again``,
    ``continue``, ``expand on that``, ``in more detail``.
    """
    if not query or len(query) > 80:
        return False
    if _FOLLOWUP_REGEX.match(query):
        return True
    # Very short pronoun-anchored questions like "what about X?" / "and X?"
    short = query.strip()
    if 0 < len(short) <= 40:
        if re.match(r"^(and|or|but|so)\b", short, re.IGNORECASE):
            return True
        if re.match(r"^what\s+about\b", short, re.IGNORECASE):
            return True
    return False


def _is_exact_or_document_query(query: str) -> bool:
    """Detect queries that should NOT be broadened by step-back/HyDE.

    Returns True for:
    - Quoted exact phrases ("some phrase")
    - Filename-specific queries (e.g., "in report.pdf", "from config.yaml")
    - Document-specific queries (e.g., "what does <filename> say about")
    - Very short exact lookups (3 words or fewer without question words)
    """
    # Quoted exact phrase
    if re.search(r'"[^"]{3,}"', query):
        return True
    # Filename reference (common extensions)
    if re.search(
        r'\b[\w\-]+\.(pdf|docx?|xlsx?|csv|txt|md|yaml|yml|json|html?|pptx?)\b',
        query,
        re.IGNORECASE,
    ):
        return True
    # Very short non-question lookups
    words = query.strip().split()
    question_words = {"what", "how", "why", "when", "where", "which", "who", "explain", "describe"}
    if len(words) <= 3 and not any(w.lower().rstrip("?") in question_words for w in words):
        return True
    return False


class QueryTransformer:
    """Transforms queries using step-back prompting for broader retrieval."""

    def __init__(self, llm_client: LLMClient):
        self._llm_client = llm_client
        self._redis_client = None
        if settings.redis_url:
            try:
                import redis
                self._redis_client = redis.from_url(settings.redis_url)
            except Exception as e:
                logger.warning("Redis connection failed, using LRU fallback: %s", e)
        # LRU cache for transform results — OrderedDict preserves insertion order,
        # move_to_end() is O(1) vs the previous list.remove() which was O(n).
        self._lru_cache: OrderedDict[str, List[Tuple[str, str]]] = OrderedDict()
        # Separate LRU cache for HyDE results (str)
        self._lru_hyde_cache: OrderedDict[str, str] = OrderedDict()

    @property
    def _cache_model(self) -> str:
        """Model identity for transform cache keys.

        RAGEngine can inject either the Thinking or Instant LLM client. Use the
        active client's configured model so the two modes cannot share cached
        query rewrites generated by different models.
        """
        return str(getattr(self._llm_client, "model", None) or settings.chat_model)

    def _make_cache_key(self, chat_model: str, transform_type: str, query_text: str) -> str:
        """Generate cache key for query transformation result."""
        key_data = json.dumps({
            "model": chat_model,
            "type": transform_type,
            "query": query_text
        }, sort_keys=True)
        return f"query_transform:{hashlib.md5(key_data.encode()).hexdigest()}"

    def _lru_get(self, key: str) -> Optional[List[Tuple[str, str]]]:
        if key in self._lru_cache:
            self._lru_cache.move_to_end(key)
            return self._lru_cache[key]
        return None

    def _lru_set(self, key: str, value: List[Tuple[str, str]]):
        if key in self._lru_cache:
            self._lru_cache.move_to_end(key)
        else:
            if len(self._lru_cache) >= 1024:
                self._lru_cache.popitem(last=False)
        self._lru_cache[key] = value

    def _lru_get_hyde(self, key: str) -> Optional[str]:
        if key in self._lru_hyde_cache:
            self._lru_hyde_cache.move_to_end(key)
            return self._lru_hyde_cache[key]
        return None

    def _lru_set_hyde(self, key: str, value: str):
        if key in self._lru_hyde_cache:
            self._lru_hyde_cache.move_to_end(key)
        else:
            if len(self._lru_hyde_cache) >= 1024:
                self._lru_hyde_cache.popitem(last=False)
        self._lru_hyde_cache[key] = value

    async def transform(self, query: str) -> List[Tuple[str, str]]:
        """
        Transform a query into [original, step_back] or [original, step_back, hyde] versions.

        Exact, quoted, filename-specific, or very short queries skip transformation
        to avoid broadening into tangential results.

        Args:
            query: Original user query

        Returns:
            List of (variant_type, text) tuples containing original query, step-back variant,
            and optionally HyDE passage. variant_type values are 'original', 'step_back', 'hyde'.
            On LLM error for step-back, returns [('original', query)] only.
            On HyDE failure alone, returns [('original', query), ('step_back', step_back_text)].
        """
        # Skip transformation for exact/document-specific queries
        if _is_exact_or_document_query(query):
            logger.info(
                "Skipping query transformation for exact/document query: '%s'",
                query[:80],
            )
            return [('original', query)]

        # Check stepback_enabled gating
        if not settings.stepback_enabled:
            logger.debug("Step-back prompting disabled, returning original query only")
            return [('original', query)]

        # Generate cache key for step-back transformation
        cache_key = self._make_cache_key(self._cache_model, "step_back", query)

        # Try Redis cache first
        if self._redis_client:
            try:
                cached = self._redis_client.get(cache_key)
                if cached:
                    logger.debug("Cache HIT (Redis) for query transformation")
                    return json.loads(cached)
            except Exception as e:
                logger.warning("Redis cache get failed: %s", e)

        # Try LRU cache
        lru_cached = self._lru_get(cache_key)
        if lru_cached:
            logger.debug("Cache HIT (LRU) for query transformation")
            return lru_cached

        # Cache miss - proceed with transformation
        try:
            messages = [
                {
                    "role": "system",
                    "content": (
                        "You are a query transformation assistant. Your task is to generate "
                        "a broader, more general version of the user's question that captures "
                        "the high-level intent and underlying concepts."
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        f"Generate a broader, more general version of this question that "
                        f"captures the underlying concept:\n"
                        f"Original: <user_query>{query}</user_query>\n"
                        f"Step-back:"
                    ),
                },
            ]

            step_back = await self._llm_client.chat_completion(
                messages=messages, max_tokens=100, temperature=settings.query_transform_temperature
            )

            if step_back and step_back.strip():
                logger.debug(
                    "Query transformation: original='%s', step_back='%s'",
                    query,
                    step_back,
                )
                variants: List[Tuple[str, str]] = [('original', query), ('step_back', step_back.strip())]
            else:
                logger.warning(
                    "Query transformation returned empty response, using original only"
                )
                variants: List[Tuple[str, str]] = [('original', query)]

        except Exception as e:
            logger.warning(
                "Query transformation failed: %s, using original query only", e
            )
            variants = [('original', query)]

        # Store in Redis if available
        if self._redis_client:
            try:
                self._redis_client.setex(
                    cache_key,
                    settings.query_transform_cache_ttl_sec,
                    json.dumps(variants)
                )
            except Exception as e:
                logger.warning("Redis cache set failed: %s", e)

        # Store in LRU cache
        self._lru_set(cache_key, variants)

        # Optionally append HyDE passage as third query variant
        if settings.hyde_enabled:
            # Check HyDE cache (both Redis and LRU)
            hyde_cache_key = self._make_cache_key(self._cache_model, "hyde", query)
            hyde_passage = None

            # Try Redis first
            if self._redis_client:
                try:
                    cached_hyde = self._redis_client.get(hyde_cache_key)
                    if cached_hyde:
                        hyde_passage = json.loads(cached_hyde)
                except Exception as e:
                    logger.warning("Redis HyDE cache get failed: %s", e)

            # Try LRU fallback
            if not hyde_passage:
                hyde_passage = self._lru_get_hyde(hyde_cache_key)

            if hyde_passage is None:
                hyde_passage = await self.generate_hyde(query)
                if hyde_passage:
                    # Store in Redis if available
                    if self._redis_client:
                        try:
                            self._redis_client.setex(
                                hyde_cache_key,
                                settings.query_transform_cache_ttl_sec,
                                json.dumps(hyde_passage)
                            )
                        except Exception as e:
                            logger.warning("Redis HyDE cache set failed: %s", e)
                    # Store in LRU cache
                    self._lru_set_hyde(hyde_cache_key, hyde_passage)

            if hyde_passage:
                variants.append(('hyde', hyde_passage))

        return variants

    async def rewrite_followup(
        self,
        query: str,
        chat_history: List[dict],
    ) -> Optional[str]:
        """Rewrite a short/referential follow-up into a self-contained question.

        Uses the most recent user/assistant exchange from ``chat_history`` to
        produce a standalone retrieval query. Returns ``None`` if there is
        insufficient history or the LLM call fails — callers should fall back
        to the original ``query`` for retrieval in that case.
        """
        if not chat_history:
            return None

        # Pull the most recent user turn (before the current message) and the
        # most recent assistant turn so the rewriter has the immediate context.
        prior_user: Optional[str] = None
        prior_assistant: Optional[str] = None
        for entry in reversed(chat_history):
            role = entry.get("role")
            content = entry.get("content")
            if not isinstance(content, str):
                continue
            if role == "assistant" and prior_assistant is None:
                prior_assistant = content
            elif role == "user" and prior_user is None:
                prior_user = content
            if prior_user and prior_assistant:
                break

        if not prior_user:
            return None

        # Cap inputs so we don't pay token cost on huge prior answers.
        prior_user_clipped = prior_user[:1000]
        prior_assistant_clipped = (prior_assistant or "")[:1500]

        system_prompt = (
            "You rewrite short follow-up chat messages into self-contained "
            "questions for document retrieval. Output ONLY the rewritten "
            "question on a single line. Do not include preambles, quotes, "
            "explanations, or trailing punctuation beyond a single '?' if "
            "appropriate."
        )
        user_prompt = (
            f"Previous user question:\n<user_query>{prior_user_clipped}</user_query>\n\n"
            f"Previous assistant answer (for context only):\n"
            f"<assistant_answer>{prior_assistant_clipped}</assistant_answer>\n\n"
            f"New follow-up message from the user:\n"
            f"<user_query>{query}</user_query>\n\n"
            "Rewrite the follow-up as a standalone question that captures what "
            "the user wants now, using the prior question/answer for missing "
            "subject matter. If the follow-up is a retry/regenerate signal "
            "(e.g. 'try again', 'again please'), output the previous user "
            "question verbatim."
        )
        try:
            response = await self._llm_client.chat_completion(
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                max_tokens=120,
                temperature=settings.query_transform_temperature,
            )
        except Exception as exc:  # noqa: BLE001 — defensive
            logger.warning("Follow-up rewrite failed: %s", exc)
            return None

        if not response:
            return None
        rewritten = response.strip().splitlines()[0].strip()
        # Strip surrounding quotes/brackets if the model added them.
        rewritten = rewritten.strip('"').strip("'").strip()
        if len(rewritten) < 3:
            return None
        return rewritten

    async def generate_hyde(self, query: str) -> Optional[str]:
        """
        Generate a hypothetical document passage that answers the query (HyDE).

        Args:
            query: The user question to generate a hypothetical answer for.

        Returns:
            A short factual passage (2-4 sentences) or None on failure/too-short response.
        """
        system_prompt = (
            "You are a knowledgeable assistant. Write a short, factual passage (2-4 sentences) "
            "that directly answers the following question. Write as if you are the document that "
            "contains the answer. Be specific and use domain-appropriate language. Do not hedge "
            "or say 'I think' — write as a confident factual passage."
        )
        user_prompt = f"Question: <user_query>{query}</user_query>\n\nPassage:"
        try:
            messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ]
            response = await self._llm_client.chat_completion(
                messages, max_tokens=350, temperature=settings.hyde_temperature
            )
            response = response.strip()
            if len(response) < 20:
                logger.info(
                    "HyDE response too short (%d chars), discarding", len(response)
                )
                return None
            logger.info("HyDE passage generated for query '%s'", query[:60])
            return response
        except Exception as e:
            logger.warning("HyDE generation failed: %s", e)
            return None
