// frontend/src/pages/AdminGroupsPage.tsx
// DESIGN SPEC — generated by Designer agent
// Coder: implement TODO items, do not change component structure or accessibility attributes

import { useState, useCallback } from "react";
import { toast } from "sonner";
import { Plus } from "lucide-react";
import { AdminGuard } from "@/components/auth/RoleGuard";
import { Button } from "@/components/ui/button";
import { GroupTable, Group } from "@/components/groups/GroupTable";
import { GroupFormDialog, GroupFormData } from "@/components/groups/GroupFormDialog";
import { ManageMembersSheet } from "@/components/groups/ManageMembersSheet";
import { ManageVaultsSheet } from "@/components/groups/ManageVaultsSheet";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import apiClient from "@/lib/api";

// ============================================================================
// API Functions (TODO: Move to api.ts)
// ============================================================================

async function createGroup(data: GroupFormData): Promise<Group> {
  const response = await apiClient.post<Group>("/groups", data);
  return response.data;
}

async function updateGroup(
  groupId: number,
  data: GroupFormData
): Promise<void> {
  await apiClient.patch(`/groups/${groupId}`, data);
}

async function deleteGroup(groupId: number): Promise<void> {
  await apiClient.delete(`/groups/${groupId}`);
}

// ============================================================================
// Main Page Component
// ============================================================================

function AdminGroupsPageContent(): JSX.Element {
  // Table refresh trigger
  const [refreshKey, setRefreshKey] = useState(0);

  // Modal/Sheet states
  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const [editDialogOpen, setEditDialogOpen] = useState(false);
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [membersSheetOpen, setMembersSheetOpen] = useState(false);
  const [vaultsSheetOpen, setVaultsSheetOpen] = useState(false);

  // Selected group for actions
  const [selectedGroup, setSelectedGroup] = useState<Group | null>(null);

  // Loading states
  const [isCreating, setIsCreating] = useState(false);
  const [isUpdating, setIsUpdating] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);

  // ============================================================================
  // Event Handlers
  // ============================================================================

  const handleRefresh = useCallback(() => {
    setRefreshKey((prev) => prev + 1);
  }, []);

  const handleCreateClick = useCallback(() => {
    setCreateDialogOpen(true);
  }, []);

  const handleEditClick = useCallback((group: Group) => {
    setSelectedGroup(group);
    setEditDialogOpen(true);
  }, []);

  const handleDeleteClick = useCallback((group: Group) => {
    setSelectedGroup(group);
    setDeleteDialogOpen(true);
  }, []);

  const handleManageMembersClick = useCallback((group: Group) => {
    setSelectedGroup(group);
    setMembersSheetOpen(true);
  }, []);

  const handleManageVaultsClick = useCallback((group: Group) => {
    setSelectedGroup(group);
    setVaultsSheetOpen(true);
  }, []);

  const handleCreateSubmit = useCallback(async (data: GroupFormData) => {
    setIsCreating(true);
    try {
      await createGroup(data);
      toast.success("Group created successfully");
      setCreateDialogOpen(false);
      handleRefresh();
    } catch (error) {
      toast.error("Failed to create group");
      throw error;
    } finally {
      setIsCreating(false);
    }
  }, [handleRefresh]);

  const handleEditSubmit = useCallback(async (data: GroupFormData) => {
    if (!selectedGroup) return;
    setIsUpdating(true);
    try {
      await updateGroup(selectedGroup.id, data);
      toast.success("Group updated successfully");
      setEditDialogOpen(false);
      handleRefresh();
    } catch (error) {
      toast.error("Failed to update group");
      throw error;
    } finally {
      setIsUpdating(false);
    }
  }, [selectedGroup, handleRefresh]);

  const handleDeleteConfirm = useCallback(async () => {
    if (!selectedGroup) return;
    setIsDeleting(true);
    try {
      await deleteGroup(selectedGroup.id);
      toast.success("Group deleted successfully");
      setDeleteDialogOpen(false);
      handleRefresh();
    } catch (error) {
      toast.error("Failed to delete group");
    } finally {
      setIsDeleting(false);
    }
  }, [selectedGroup, handleRefresh]);

  const handleMembersSave = useCallback(async (userIds: number[]) => {
    if (!selectedGroup) return;
    try {
      await apiClient.put(`/groups/${selectedGroup.id}/members`, { user_ids: userIds });
      toast.success("Group members updated");
      setMembersSheetOpen(false);
      handleRefresh();
    } catch (error) {
      const message = error instanceof Error ? error.message : "Failed to update group members";
      toast.error(message);
      throw error;
    }
  }, [selectedGroup, handleRefresh]);

  const handleVaultsSave = useCallback(async (vaultIds: number[]) => {
    if (!selectedGroup) return;
    try {
      await apiClient.put(`/groups/${selectedGroup.id}/vaults`, { vault_ids: vaultIds });
      toast.success("Vault access updated");
      setVaultsSheetOpen(false);
      handleRefresh();
    } catch (error) {
      const message = error instanceof Error ? error.message : "Failed to update vault access";
      toast.error(message);
      throw error;
    }
  }, [selectedGroup, handleRefresh]);

  // ============================================================================
  // Render
  // ============================================================================

  return (
    <div className="space-y-6 animate-in fade-in duration-300" role="main" aria-label="Groups Management">
      {/* Header */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Groups</h1>
          <p className="text-muted-foreground mt-1">
            Manage user groups and their vault access permissions
          </p>
        </div>
        <Button onClick={handleCreateClick} aria-label="Create new group">
          <Plus className="mr-2 h-4 w-4" aria-hidden="true" />
          Create Group
        </Button>
      </div>

      {/* Groups Table */}
      <GroupTable
        key={refreshKey}
        onEdit={handleEditClick}
        onDelete={handleDeleteClick}
        onManageMembers={handleManageMembersClick}
        onManageVaults={handleManageVaultsClick}
      />

      {/* Create Group Dialog */}
      <GroupFormDialog
        mode="create"
        open={createDialogOpen}
        onOpenChange={setCreateDialogOpen}
        onSubmit={handleCreateSubmit}
        isLoading={isCreating}
      />

      {/* Edit Group Dialog */}
      <GroupFormDialog
        mode="edit"
        group={selectedGroup}
        open={editDialogOpen}
        onOpenChange={setEditDialogOpen}
        onSubmit={handleEditSubmit}
        isLoading={isUpdating}
      />

      {/* Manage Members Sheet */}
      <ManageMembersSheet
        group={selectedGroup}
        open={membersSheetOpen}
        onOpenChange={setMembersSheetOpen}
        onSave={handleMembersSave}
      />

      {/* Manage Vaults Sheet */}
      <ManageVaultsSheet
        group={selectedGroup}
        open={vaultsSheetOpen}
        onOpenChange={setVaultsSheetOpen}
        onSave={handleVaultsSave}
      />

      {/* Delete Confirmation Dialog */}
      <Dialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}>
        <DialogContent className="sm:max-w-[400px]" aria-labelledby="delete-title" aria-describedby="delete-desc">
          <DialogHeader>
            <DialogTitle id="delete-title">Delete Group</DialogTitle>
            <DialogDescription id="delete-desc">
              Are you sure you want to delete <strong>{selectedGroup?.name}</strong>? 
              This action cannot be undone. Members will lose access to vaults through this group.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter className="flex-col gap-2 sm:flex-row">
            <Button
              type="button"
              variant="outline"
              onClick={() => setDeleteDialogOpen(false)}
              disabled={isDeleting}
              className="w-full sm:w-auto"
            >
              Cancel
            </Button>
            <Button
              type="button"
              variant="destructive"
              onClick={handleDeleteConfirm}
              disabled={isDeleting}
              className="w-full sm:w-auto"
              aria-label="Confirm delete group"
            >
              {isDeleting ? "Deleting..." : "Delete Group"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

export default function AdminGroupsPage(): JSX.Element {
  return (
    <AdminGuard>
      <AdminGroupsPageContent />
    </AdminGuard>
  );
}
